//
//  liste_instr.h
//  desassembleur
//
//  Created by Hubert Godfroy on 24/03/12.
//  Copyright (c) 2012 Mines de Nancy. All rights reserved.
//

/**
 * file liste_instr.h
 *  
 */

#ifndef desassembleur_liste_instr_h
#define desassembleur_liste_instr_h

#include "instruction.h"

Instruction*  init_add(void);
Instruction*  init_and(void);
Instruction*  init_mov(void);

/* ====================================== opcodes_A_M */
Instruction*  init_aaa_(void);
Instruction*  init_aad_(void);
Instruction*  init_aas_(void);
Instruction*  init_aam_(void);
Instruction*  init_add_EbGb(void);
Instruction*  init_add_EvGv(void);
Instruction*  init_add_GbEb(void);
Instruction*  init_add_GvEv(void);
Instruction*  init_add_ALIb(void);
Instruction*  init_add_eAX_Iv(void);
Instruction*  init_adc_ALIb(void);
Instruction*  init_adc_eAX_Iv(void);
Instruction*  init_adc_EbGb(void);
Instruction*  init_adc_EvGv(void);
Instruction*  init_adc_GbEb(void);
Instruction*  init_adc_GvEv(void);
Instruction*  init_and_EbGb(void);
Instruction*  init_and_ALIb(void);
Instruction*  init_and_eAX_Iv(void);
Instruction*  init_and_EvGv(void);
Instruction*  init_and_GbEb(void);
Instruction*  init_and_GvEv(void);
Instruction*  init_arpl_(void);
Instruction*  init_bound_(void);
Instruction*  init_bswap_eax(void);
Instruction*  init_bswap_ebp(void);
Instruction*  init_bswap_ebx(void);
Instruction*  init_bswap_ecx(void);
Instruction*  init_bswap_edi(void);
Instruction*  init_bswap_edx(void);
Instruction*  init_bswap_esi(void);
Instruction*  init_bswap_esp(void);
Instruction*  init_bsf_GvEv(void);
Instruction*  init_bsr_GvEv(void);
Instruction*  init_btc_EvGv(void);
Instruction*  init_btr_EvGv(void);
Instruction*  init_bt_EvGv(void);
Instruction*  init_bts_EvGv(void);
Instruction*  init_callf_(void);
Instruction*  init_call_(void);
Instruction*  init_cdq_(void);
Instruction*  init_clts_(void);
Instruction*  init_cmc_(void);
Instruction*  init_cmovo_(void);
Instruction*  init_cmovno_(void);
Instruction*  init_cmovb_(void);
Instruction*  init_cmovnb_(void);
Instruction*  init_cmove_(void);
Instruction*  init_cmovne_(void);
Instruction*  init_cmovbe_(void);
Instruction*  init_cmovnbe_(void);
Instruction*  init_cmovs_(void);
Instruction*  init_cmovns_(void);
Instruction*  init_cmovp_(void);
Instruction*  init_cmovnp_(void);
Instruction*  init_cmovl_(void);
Instruction*  init_cmovnl_(void);
Instruction*  init_cmovle_(void);
Instruction*  init_cmovnle_(void);
Instruction*  init_cmpx_EbGb(void);
Instruction*  init_cmpx_EvGv(void);
Instruction*  init_cmp_EbGb(void);
Instruction*  init_cmp_EvGv(void);
Instruction*  init_cmp_GbEb(void);
Instruction*  init_cmp_GvEv(void);
Instruction*  init_cmp_ALIb(void);
Instruction*  init_cmp_eAX_Iv(void);
Instruction*  init_cmpsb_(void);
Instruction*  init_cmps_(void);
Instruction*  init_cwde_(void);
Instruction*  init_clc_(void);
Instruction*  init_cld_(void);
Instruction*  init_cli_(void);
Instruction*  init_cpuid_(void);
Instruction*  init_daa_(void);
Instruction*  init_das_(void);
Instruction*  init_dec_eax(void);
Instruction*  init_dec_ecx(void);
Instruction*  init_dec_edx(void);
Instruction*  init_dec_ebx(void);
Instruction*  init_dec_esp(void);
Instruction*  init_dec_ebp(void);
Instruction*  init_dec_esi(void);
Instruction*  init_dec_edi(void);
Instruction*  init_enter_(void);
Instruction*  init_femms_(void);
Instruction*  init_hlt_(void);
Instruction*  init_invd_(void);
Instruction*  init_inc_eax(void);
Instruction*  init_inc_ecx(void);
Instruction*  init_inc_edx(void);
Instruction*  init_inc_ebx(void);
Instruction*  init_inc_esp(void);
Instruction*  init_inc_ebp(void);
Instruction*  init_inc_esi(void);
Instruction*  init_inc_edi(void);
Instruction*  init_iret_(void);
Instruction*  init_in_ALDX(void);
Instruction*  init_in_ALIb(void);
Instruction*  init_in_eAX_Ib(void);
Instruction*  init_insb_(void);
Instruction*  init_ins_(void);
Instruction*  init_into_(void);
Instruction*  init_in_eAX(void);
Instruction*  init_int_(void);
Instruction*  init_int1_(void);
Instruction*  init_int3_(void);
Instruction*  init_imul_GvEvIv(void);
Instruction*  init_imul_GvEv(void);
Instruction*  init_imul_GvEvIb(void);
Instruction*  init_jo_(void);
Instruction*  init_jno_(void);
Instruction*  init_jc_(void);
Instruction*  init_jnc_(void);
Instruction*  init_je_(void);
Instruction*  init_jne_(void);
Instruction*  init_jbe_(void);
Instruction*  init_jnbe_(void);
Instruction*  init_js_(void);
Instruction*  init_jns_(void);
Instruction*  init_jp_(void);
Instruction*  init_jnp_(void);
Instruction*  init_jl_(void);
Instruction*  init_jnl_(void);
Instruction*  init_jle_(void);
Instruction*  init_jnle_(void);
Instruction*  init_jo_near(void);
Instruction*  init_jno_near(void);
Instruction*  init_jc_near(void);
Instruction*  init_jnc_near(void);
Instruction*  init_je_near(void);
Instruction*  init_jne_near(void);
Instruction*  init_jbe_near(void);
Instruction*  init_ja_near(void);
Instruction*  init_js_near(void);
Instruction*  init_jns_near(void);
Instruction*  init_jp_near(void);
Instruction*  init_jnp_near(void);
Instruction*  init_jl_near(void);
Instruction*  init_jnl_near(void);
Instruction*  init_jle_near(void);
Instruction*  init_jnle_near(void);
Instruction*  init_jecxz_(void);
Instruction*  init_jmp_near(void);
Instruction*  init_jmp_far(void);
Instruction*  init_jmp_short(void);
Instruction*  init_lahf_(void);
Instruction*  init_lar_GvEw(void);
Instruction*  init_lds_GvM(void);
Instruction*  init_leave_(void);
Instruction*  init_lea_GvM(void);
Instruction*  init_les_GvM(void);
Instruction*  init_lodsb_(void);
Instruction*  init_lodsw_(void);
Instruction*  init_loop_(void);
Instruction*  init_loope_(void);
Instruction*  init_loopne_(void);
Instruction*  init_lsl_GvEw(void);
Instruction*  init_lss_Mp(void);
Instruction*  init_lfs_Mp(void);
Instruction*  init_lgs_Mp(void);
Instruction*  init_mov_RdCd(void);
Instruction*  init_mov_RdDd(void);
Instruction*  init_mov_CdRd(void);
Instruction*  init_mov_DdRd(void);
Instruction*  init_mov_EbGb(void);
Instruction*  init_mov_EvGv(void);
Instruction*  init_mov_GbEb(void);
Instruction*  init_mov_GvEv(void);
Instruction*  init_mov_ALOb(void);
Instruction*  init_mov_eAXOv(void);
Instruction*  init_mov_ObAL(void);
Instruction*  init_mov_OveAX(void);
Instruction*  init_mov_ALIb(void);
Instruction*  init_mov_CLIb(void);
Instruction*  init_mov_DLIb(void);
Instruction*  init_mov_BLIb(void);
Instruction*  init_mov_AHIb(void);
Instruction*  init_mov_CHIb(void);
Instruction*  init_mov_DHIb(void);
Instruction*  init_mov_BHIb(void);
Instruction*  init_movs_(void);
Instruction*  init_movsw_(void);
Instruction*  init_movzx_GvEb(void);
Instruction*  init_movsx_GvEb(void);
Instruction*  init_movzx_GvEw(void);
Instruction*  init_movsx_GvEw(void);
Instruction*  init_mov_EAX(void);
Instruction*  init_mov_ECX(void);
Instruction*  init_mov_EDX(void);
Instruction*  init_mov_EBX(void);
Instruction*  init_mov_ESP(void);
Instruction*  init_mov_EBP(void);
Instruction*  init_mov_ESI(void);
Instruction*  init_mov_EDI(void);
Instruction*  init_mov_EbIb(void);
Instruction*  init_mov_EvIv(void);
Instruction*  init_mov_EwSreg(void);
Instruction*  init_mov_SregEw(void);

/* ====================================== opcodes_N_Z */
Instruction*  init_nop_(void);
Instruction*  init_nop_Ev(void);
Instruction*  init_hint_nop(void);
Instruction*  init_or_EbGb(void);
Instruction*  init_or_EvGv(void);
Instruction*  init_or_GbEb(void);
Instruction*  init_or_GvEv(void);
Instruction*  init_or_ALIb(void);
Instruction*  init_or_eAX_Iv(void);
Instruction*  init_outsb_(void);
Instruction*  init_outsw_(void);
Instruction*  init_out_IbAL(void);
Instruction*  init_out_Ib_eAX(void);
Instruction*  init_out_DXAL(void);
Instruction*  init_out_DXeAX(void);
Instruction*  init_pop_Ev(void);
Instruction*  init_pop_eax(void);
Instruction*  init_pop_ecx(void);
Instruction*  init_pop_edx(void);
Instruction*  init_pop_ebx(void);
Instruction*  init_pop_esp(void);
Instruction*  init_pop_ebp(void);
Instruction*  init_pop_esi(void);
Instruction*  init_pop_edi(void);
Instruction*  init_pop_ds(void);
Instruction*  init_pop_es(void);
Instruction*  init_pop_fs(void);
Instruction*  init_pop_gs(void);
Instruction*  init_pop_ss(void);
Instruction*  init_popfd_(void);
Instruction*  init_popad_(void);
Instruction*  init_push_eax(void);
Instruction*  init_push_ecx(void);
Instruction*  init_push_edx(void);
Instruction*  init_push_ebx(void);
Instruction*  init_push_esp(void);
Instruction*  init_push_ebp(void);
Instruction*  init_push_esi(void);
Instruction*  init_push_edi(void);
Instruction*  init_push_cs(void);
Instruction*  init_push_ds(void);
Instruction*  init_push_es(void);
Instruction*  init_push_fs(void);
Instruction*  init_push_gs(void);
Instruction*  init_push_ss(void);
Instruction*  init_pushfd_(void);
Instruction*  init_pushad_(void);
Instruction*  init_push_Iv(void);
Instruction*  init_push_Ib(void);
Instruction*  init_pushfd_(void);
Instruction*  init_pushad_(void);
Instruction*  init_retn_(void);
Instruction*  init_ret_(void);
Instruction*  init_retf_(void);
Instruction*  init_retf_Iw(void);
Instruction*  init_rdtsc_(void);
Instruction*  init_rdmsr_(void);
Instruction*  init_rdpmc_(void);
Instruction*  init_rsm_(void);
Instruction*  init_sysenter_(void);
Instruction*  init_sysexit_(void);
Instruction*  init_sahf_(void);
Instruction*  init_salc_(void);
Instruction*  init_scasb_(void);
Instruction*  init_scas_(void);
Instruction*  init_stc_(void);
Instruction*  init_sti_(void);
Instruction*  init_stos_(void);
Instruction*  init_stosw_(void);
Instruction*  init_syscall_(void);
Instruction*  init_sysret_(void);
Instruction*  init_sbb_EbGb(void);
Instruction*  init_sbb_EvGv(void);
Instruction*  init_sbb_GbEb(void);
Instruction*  init_sbb_GvEv(void);
Instruction*  init_sbb_ALIb(void);
Instruction*  init_sbb_eAX_Iv(void);
Instruction*  init_seto_(void);
Instruction*  init_setno_(void);
Instruction*  init_setb_(void);
Instruction*  init_setnb_(void);
Instruction*  init_sete_(void);
Instruction*  init_setne_(void);
Instruction*  init_setbe_(void);
Instruction*  init_setnbe_(void);
Instruction*  init_sets_(void);
Instruction*  init_setns_(void);
Instruction*  init_setp_(void);
Instruction*  init_setnp_(void);
Instruction*  init_setnge_(void);
Instruction*  init_setge_(void);
Instruction*  init_setle_(void);
Instruction*  init_setnle_(void);
Instruction*  init_shld_EvGvIb(void);
Instruction*  init_shld_EvGvCL(void);
Instruction*  init_shrd_EvGvIb(void);
Instruction*  init_shrd_EvGvCL(void);
Instruction*  init_std_(void);
Instruction*  init_sub_ALIb(void);
Instruction*  init_sub_eAX_Iv(void);
Instruction*  init_sub_EbGb(void);
Instruction*  init_sub_EvGv(void);
Instruction*  init_sub_GbEb(void);
Instruction*  init_sub_GvEv(void);
Instruction*  init_test_ALIb(void);
Instruction*  init_test_eAX_Iv(void);
Instruction*  init_test_EbGb(void);
Instruction*  init_test_EvGv(void);
Instruction*  init_test_GbEb(void);
Instruction*  init_test_GvEv(void);
Instruction*  init_ud2_(void);
Instruction*  init_vmread_(void);
Instruction*  init_vmwrite_(void);
Instruction*  init_wbinvd_(void);
Instruction*  init_wait_(void);
Instruction*  init_wrmsr_(void);
Instruction*  init_xadd_EbGb(void);
Instruction*  init_xadd_EvGv(void);
Instruction*  init_xchg_EbGb(void);
Instruction*  init_xchg_ebp(void);
Instruction*  init_xchg_ebx(void);
Instruction*  init_xchg_ecx(void);
Instruction*  init_xchg_edi(void);
Instruction*  init_xchg_edx(void);
Instruction*  init_xchg_esi(void);
Instruction*  init_xchg_esp(void);
Instruction*  init_xchg_EvGv(void);
Instruction*  init_xlat_(void);
Instruction*  init_xor_ALIb(void);
Instruction*  init_xor_eAX_Iv(void);
Instruction*  init_xor_EbGb(void);
Instruction*  init_xor_EvGv(void);
Instruction*  init_xor_GbEb(void);
Instruction*  init_xor_GvEv(void);

/* ====================================== opcodes_Grp1 */
Instruction*  init_G1_EbIb(void);
Instruction*  init_G1_EbIb2(void);
Instruction*  init_G1_EvIv(void);
Instruction*  init_G1_EvIb(void);

/* ====================================== opcodes_Grp2 */
Instruction*  init_G2_EbIb(void);
Instruction*  init_G2_EvIb(void);
Instruction*  init_G2_Ev1(void);
Instruction*  init_G2_Eb1(void);
Instruction*  init_G2_EbCL(void);
Instruction*  init_G2_EvCL(void);

/* ====================================== opcodes_Grp3 */
Instruction*  init_G3_Eb(void);
Instruction*  init_G3_Ev(void);

/* ====================================== opcodes_Grp4 */
Instruction*  init_G4_Eb(void);

/* ====================================== opcodes_Grp5 */
Instruction*  init_G5_Ev(void);

/* ====================================== opcodes_Grp6 */
Instruction*  init_G6_(void);

/* ====================================== opcodes_Grp7 */
Instruction*  init_G7_(void);

/* ====================================== opcodes_Grp8 */
Instruction*  init_G8_EvIb(void);

/* ====================================== opcodes_Grp9 */
Instruction*  init_G9_(void);

/* ====================================== opcodes_Grp12 */
Instruction*  init_G12_(void);

/* ====================================== opcodes_Grp13 */
Instruction*  init_G13_(void);

/* ====================================== opcodes_Grp14 */
Instruction*  init_G14_(void);

/* ====================================== opcodes_Grp15 */
Instruction*  init_G15_(void);

/* ====================================== opcodes_Grp16 */
Instruction*  init_G16_(void);

/* ====================================== opcodes_FPU */
Instruction*  init_D8_(void);
Instruction*  init_D9_(void);
Instruction*  init_DA_(void);
Instruction*  init_DB_(void);
Instruction*  init_DC_(void);
Instruction*  init_DD_(void);
Instruction*  init_DE_(void);
Instruction*  init_DF_(void);

/* ====================================== opcodes_MMX */
Instruction*  init_emms_(void);
Instruction*  init_movd_EP(void);
Instruction*  init_movd_PE(void);
Instruction*  init_movq_PQ(void);
Instruction*  init_movq_QP(void);
Instruction*  init_movq_WV(void);
Instruction*  init_pabsb_(void);
Instruction*  init_pabsd_(void);
Instruction*  init_pabsw_(void);
Instruction*  init_packssdw_(void);
Instruction*  init_packsswb_(void);
Instruction*  init_packuswb_(void);
Instruction*  init_paddb_(void);
Instruction*  init_paddd_(void);
Instruction*  init_paddsb_(void);
Instruction*  init_paddsw_(void);
Instruction*  init_paddusb_(void);
Instruction*  init_paddusw_(void);
Instruction*  init_paddw_(void);
Instruction*  init_pandn_(void);
Instruction*  init_pand_(void);
Instruction*  init_pcmpeqb_(void);
Instruction*  init_pcmpeqd_(void);
Instruction*  init_pcmpeqw_(void);
Instruction*  init_pcmpgtb_(void);
Instruction*  init_pcmpgtd_(void);
Instruction*  init_pcmpgtw_(void);
Instruction*  init_pmulhw_(void);
Instruction*  init_pmullw_(void);
Instruction*  init_pmaddwd_(void);
Instruction*  init_por_(void);
Instruction*  init_pslld_(void);
Instruction*  init_psllq_(void);
Instruction*  init_psllw_(void);
Instruction*  init_psrld_(void);
Instruction*  init_psrlq_(void);
Instruction*  init_psrlw_(void);
Instruction*  init_psrad_(void);
Instruction*  init_psraw_(void);
Instruction*  init_psubb_(void);
Instruction*  init_psubd_(void);
Instruction*  init_psubsb_(void);
Instruction*  init_psubsw_(void);
Instruction*  init_psubusb_(void);
Instruction*  init_psubusw_(void);
Instruction*  init_psubw_(void);
Instruction*  init_punpckhbw_(void);
Instruction*  init_punpckhdq_(void);
Instruction*  init_punpckhwd_(void);
Instruction*  init_punpcklbw_(void);
Instruction*  init_punpckldq_(void);
Instruction*  init_punpcklwd_(void);
Instruction*  init_pxor_(void);

/* ====================================== opcodes_SSE */
Instruction*  init_addps_VW(void);
Instruction*  init_addsubpd_(void);
Instruction*  init_andnps_VW(void);
Instruction*  init_andps_VW(void);
Instruction*  init_blendpd_(void);
Instruction*  init_blendps_(void);
Instruction*  init_blendvpd_(void);
Instruction*  init_blendvps_(void);
Instruction*  init_cmpps_VW(void);
Instruction*  init_crc32_GvEb(void);
Instruction*  init_crc32_GvEv(void);
Instruction*  init_comiss_VW(void);
Instruction*  init_cvtdq2ps_(void);
Instruction*  init_cvtpd2dq_(void);
Instruction*  init_cvtpi2ps_(void);
Instruction*  init_cvtps2pd_(void);
Instruction*  init_cvtps2pi_(void);
Instruction*  init_cvttps2pi_(void);
Instruction*  init_dppd_(void);
Instruction*  init_dpps_(void);
Instruction*  init_divps_VW(void);
Instruction*  init_extractps_(void);
Instruction*  init_haddpd_VW(void);
Instruction*  init_hsubpd_VW(void);
Instruction*  init_insertps_(void);
Instruction*  init_lddqu_(void);
Instruction*  init_maskmovq_(void);
Instruction*  init_maxps_VW(void);
Instruction*  init_minps_VW(void);
Instruction*  init_movaps_VW(void);
Instruction*  init_movaps_WV(void);
Instruction*  init_movhps_MV(void);
Instruction*  init_movhps_VM(void);
Instruction*  init_movlps_MV(void);
Instruction*  init_movlps_VM(void);
Instruction*  init_movmskps_(void);
Instruction*  init_movntdqa_(void);
Instruction*  init_movnti_(void);
Instruction*  init_movntps_(void);
Instruction*  init_movntq_(void);
Instruction*  init_movups_VW(void);
Instruction*  init_movups_WV(void);
Instruction*  init_mpsadbw_(void);
Instruction*  init_mulps_VW(void);
Instruction*  init_orps_VW(void);
Instruction*  init_packusdw_(void);
Instruction*  init_paddq_(void);
Instruction*  init_pavgb_(void);
Instruction*  init_pavgw_(void);
Instruction*  init_palignr_(void);
Instruction*  init_pblendvb_(void);
Instruction*  init_pblendw_(void);
Instruction*  init_pcmpeqq_(void);
Instruction*  init_pcmpestri_(void);
Instruction*  init_pcmpestrm_(void);
Instruction*  init_pcmpgtq_(void);
Instruction*  init_pcmpistri_(void);
Instruction*  init_pcmpistrm_(void);
Instruction*  init_pextrb_(void);
Instruction*  init_pextrd_(void);
Instruction*  init_pextrw2_(void);
Instruction*  init_pextrw_(void);
Instruction*  init_phaddd_(void);
Instruction*  init_phaddsw_(void);
Instruction*  init_phaddw_(void);
Instruction*  init_phminposuw_(void);
Instruction*  init_phsubd_(void);
Instruction*  init_phsubsw_(void);
Instruction*  init_phsubw_(void);
Instruction*  init_pinsrb_(void);
Instruction*  init_pinsrd_(void);
Instruction*  init_pinsrw_(void);
Instruction*  init_pmaxsb_(void);
Instruction*  init_pmaxsd_(void);
Instruction*  init_pmaxsw_(void);
Instruction*  init_pmaxub_(void);
Instruction*  init_pmaxud_(void);
Instruction*  init_pmaxuw_(void);
Instruction*  init_pminsb_(void);
Instruction*  init_pminsd_(void);
Instruction*  init_pminsw_(void);
Instruction*  init_pminub_(void);
Instruction*  init_pminud_(void);
Instruction*  init_pminuw_(void);
Instruction*  init_pmaddubsw_(void);
Instruction*  init_pmovmskb_(void);
Instruction*  init_pmovsxbd_(void);
Instruction*  init_pmovsxbq_(void);
Instruction*  init_pmovsxbw_(void);
Instruction*  init_pmovsxdq_(void);
Instruction*  init_pmovsxwd_(void);
Instruction*  init_pmovsxwq_(void);
Instruction*  init_pmovzxbd_(void);
Instruction*  init_pmovzxbq_(void);
Instruction*  init_pmovzxbw_(void);
Instruction*  init_pmovzxdq_(void);
Instruction*  init_pmovzxwd_(void);
Instruction*  init_pmovzxwq_(void);
Instruction*  init_pmuldq_(void);
Instruction*  init_pmulhrsw_(void);
Instruction*  init_pmulhuw_(void);
Instruction*  init_pmulhw_(void);
Instruction*  init_pmulld_(void);
Instruction*  init_pmullw_(void);
Instruction*  init_pmuludq_(void);
Instruction*  init_popcnt_(void);
Instruction*  init_psadbw_(void);
Instruction*  init_pshufb_(void);
Instruction*  init_pshufw_(void);
Instruction*  init_psignb_(void);
Instruction*  init_psignd_(void);
Instruction*  init_psignw_(void);
Instruction*  init_psubq_(void);
Instruction*  init_ptest_(void);
Instruction*  init_punpcklqdq_(void);
Instruction*  init_punpckhqdq_(void);
Instruction*  init_rcpps_(void);
Instruction*  init_roundpd_(void);
Instruction*  init_roundps_(void);
Instruction*  init_roundsd_(void);
Instruction*  init_roundss_(void);
Instruction*  init_rsqrtps_(void);
Instruction*  init_shufps_(void);
Instruction*  init_sqrtps_VW(void);
Instruction*  init_subps_VW(void);
Instruction*  init_ucomiss_VW(void);
Instruction*  init_unpckhps_(void);
Instruction*  init_unpcklps_(void);
Instruction*  init_xorps_VW(void);

/* ====================================== opcodes_AES */
Instruction*  init_aesimc(void);
Instruction*  init_aesdec(void);
Instruction*  init_aesdeclast(void);
Instruction*  init_aesenc(void);
Instruction*  init_aesenclast(void);
Instruction*  init_aeskeygen(void);

/* ====================================== opcodes_CLMUL */
Instruction*  init_pclmulqdq_(void);

/*-------------------------------------------------------*/
test* init_test(void);

#endif
